# Generated by Django 4.2.4 on 2023-11-01 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UsualWebsite", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sportsproduct",
            name="image",
            field=models.FileField(upload_to=""),
        ),
    ]
