# Generated by Django 4.2.4 on 2023-11-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UsualWebsite", "0002_alter_sportsproduct_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sportsproduct",
            name="image",
            field=models.CharField(max_length=200),
        ),
    ]
